title: LMU Computer Science “Hacking” Guidelines
email: dondi@lmu.edu
description: Guidelines website for successfully “hacking” Computer Science at Loyola Marymount University—mostly hacking-as-programming, but maybe some life hacks too.
github_username: lmucs

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        none

# Server
destination:      _gh_pages
host:             127.0.0.1
baseurl:          /hacking-guidelines
encoding:         UTF-8
